### ISSUE TITLE
代码42行关于unsigned占用字节数的疑问

### ISSUE THREAD

**Issue by guluting** [wuwenbin/buddy2#1]
42行的代码  `for (i = 0; i < 2 * size - 1; ++i) `
如果是遍历所有longest中数据的话，应该是 ：
`for(int i=0; i < size * 2 * sizeof(uint32_t); i++)`

我的理解是，在生成内存数据的时候使用了`self = (struct buddy2*)ALLOC( 2 * size * sizeof(unsigned));`
unsigned假如占4字节，所以42行代码直接写成`for (i = 0; i < 2 * size - 1; ++i) `我感觉会有些问题。

**Comment by wuwenbin** [comment]
buddy2结构一共分配了2*size个unsigned，1个unsigned给了size域，剩下2*size-1个unsigned给longest域了，所以后面longest就是遍历2*size-1次。
至于sizeof(uint32_t)，我这是直接通过下标给unsigned数组赋值的，每个值就是个unsigned，和字节无关，不需要考虑字节的问题，不乘sizeof(uint32_t)。
